name: Regeneration
version: '${project.version}'
main: mc.craig.software.regeneration.Regeneration
api-version: '1.20'
load: STARTUP
commands:
  regen:
    description: Set the number of regenerations
    usage: /regen set-regens <AMOUNTHERE>
permissions:
  regeneration.can_regenerate:
    description: Allows the player to regenerate
  regeneration.set_regens:
    description: Allows the player to manipulate their regeneration amount via commands
